### ISSUE TITLE
Notice of Copyright Violation

### ISSUE THREAD

**Issue by Iconoclasta** [XBIncognito/public#2]
This is an official notice of Copyright violation against the PIVX developers in which this project has been forked from. The MIT copyright license, and subsequent copyright headers in source files have been modified to explicitly exclude the PIVX developers from all copyrights.

You are hereby notified of an intention to pursue further action if this issue is not acknowledged and formally addressed with a resolution timeframe commitment wherein. Failure to acknowledge and correct the violation will result in a formal DMCA takedown notice filed with GitHub Proper after no less than five business days from the date of this notice.

Explicit acknowledgement and referencing progress to maintain compliance MUST be noted in this issue's comments or referred to in any subsequent pull requests to this repository

File in question:

      public/LICENSE

**Comment by galimba** [comment]
Acknowledged! We are terribly sorry for the mistake. If you were to see the history on our public repository, you'd notice that the Licence was in fact hosted within **public/COPYING**, the same place as PIVX.

The file you pointed out **(public/LICENCE)** was in fact contradicting the actual Licence and has now been fixed accordingly.

We're terribly sorry for the inconvenience and kindly thank you for noticing the issue.

Best regards!

The XBI team

**Comment by Iconoclasta** [comment]
Everything seems in order, thanks for the collaboration.
The PIVX team will be paying closer attention for copyright violations, which will then allow healthier and mutual relationships with our various forks. We have plans of forming a network we can all mutually benefit from. I would love to keep you in the loop about such progress.
